### ISSUE TITLE
StartVCData 继承UIViewController

### ISSUE THREAD

**Issue by ttttfix** [Learning-Software-Development/bilibili-fake#1]
这个继承NSObject就行了吧，另外看你项目里面有AFNetworking  为何下载数据的时候没有使用呢？数据请求成功后对数据的判断加工另建一个方法为好

**Comment by cezres** [comment]
唔，这里是我同学写的，他还没改。
网络请求封装的代码在/Class/Common/Request 文件夹下。
目前代码大致的组织是网络请求继承BaseRequest设置参数，Model做数据请求、处理。
除了start、find文件夹下的业务代码都是按照这个套路写的。

**Comment by cezres** [comment]
写这个一方面的目的就是有个具体的场景比较方便讨论hhh

**Comment by ghost** [comment]
高仿真哈哈，来看下代码，找找有没有值得学习的东西

**Comment by caixuehao** [comment]
我的锅。本来写着玩儿的，没怎么仔细检查。创建文件时没注意。等我把手头的事情搞完了，会把代码重写一下，改的和他一样，方便看的。
