### ISSUE TITLE
楼主报错

### ISSUE THREAD

**Issue by shaohuihu** [Learning-Software-Development/bilibili-fake#2]
![123](https://cloud.githubusercontent.com/assets/6970321/18302418/63fd3ae8-750a-11e6-9dcc-68b39f4087bc.png)

是不是还要设置什么？

**Comment by shaohuihu** [comment]
希望回复！

**Comment by cezres** [comment]
你是不是走错门了？233333
项目里面没有这块代码呀
@shaohuihu

**Comment by caixuehao** [comment]
https://github.com/MichaelHuyp/Bilibili_Wuxianda

**Comment by caixuehao** [comment]
大兄弟你是不是进错帖子了

**Comment by lizhengjin** [comment]
我重新下载了,没问题 啊 ,你在终端上  只用cd 到这个文件夹下 ,pod install 就 可以了

**Comment by shaohuihu** [comment]
是弄错了.呵呵
