### ISSUE TITLE
About the URLRouter

### ISSUE THREAD

**Issue by littledogboy** [Learning-Software-Development/bilibili-fake#3]
URLRouter 里面的一个方法，这里应该是手误吧。
- (void)unregisterURLPattern:(NSString *)URLPattern {
  [self unregisterURLPattern:URLPattern]; 
  //    [self unregisterWithKey:URLPattern]; 
  }

**Comment by cezres** [comment]
@littledogboy   额...我傻了....   刚刚改掉了，多谢提醒！~
