### ISSUE TITLE
看了下代码 写的真的很好~

### ISSUE THREAD

**Issue by MichaelHuyp** [Learning-Software-Development/bilibili-fake#4]
赞 同是B站发烧友 - ( ゜- ゜)つロ 乾杯~

**Comment by cezres** [comment]
嗯嗯，小伙伴你好！~  
因为兴趣和练习的目的就试着写写看，本来只是计划做下界面部分和同学交流交流代码的，没想到之后抓包到那么多接口2333 
唔  看来这个代码还是有一些人看到的  话说现在再看之前的代码感觉挺坑的...  我抽空再改改!!~
( ゜- ゜)つロ 乾杯~
